// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJL3Z15jv3mhddzPHXxkM2lQL5NlI2I6A',
    appId: '1:841340669875:web:2add7d555094702ee005c6',
    messagingSenderId: '841340669875',
    projectId: 'mindpark-39aaa',
    authDomain: 'mindpark-39aaa.firebaseapp.com',
    storageBucket: 'mindpark-39aaa.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9q4ey5oxnRl3ZLuPP2JlRX_hsoiz647c',
    appId: '1:841340669875:android:d3fbe85a6f51625fe005c6',
    messagingSenderId: '841340669875',
    projectId: 'mindpark-39aaa',
    storageBucket: 'mindpark-39aaa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0rT-sk7_TLssBphS3IUjJFwXGOyXk20o',
    appId: '1:841340669875:ios:e4b3ffb5701ad696e005c6',
    messagingSenderId: '841340669875',
    projectId: 'mindpark-39aaa',
    storageBucket: 'mindpark-39aaa.appspot.com',
    iosBundleId: 'com.example.mindgames',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0rT-sk7_TLssBphS3IUjJFwXGOyXk20o',
    appId: '1:841340669875:ios:97f64d99d03bda63e005c6',
    messagingSenderId: '841340669875',
    projectId: 'mindpark-39aaa',
    storageBucket: 'mindpark-39aaa.appspot.com',
    iosBundleId: 'com.example.mindgames.RunnerTests',
  );
}
